name: Deploy Backend to Oracle VM

on:
  push:
    branches: [ main ]
    paths:
      - 'Clush_Back_SpringBoot/**'
      - '!README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, x64]  # CentOS 환경에서 실행
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # self-hosted 러너라면 JDK가 이미 설치되어 있을 가능성이 높음
      # 필요하다면 JAVA_HOME만 설정
      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

  deploy:
    needs: build
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Backend to Oracle VM
        run: |
          ssh -v -o StrictHostKeyChecking=no dio@192.168.56.1 'bash -s' << 'EOF'
            export SUDO_PASSWORD="${{ secrets.SUDO_PASSWORD }}"
            /clush/deploy/deploy_back.sh
          EOF
